name: GitHub Actions Demo

on:
  push:
    branches: main
    paths-ignore: [.github/**]
  pull_request:
    branches: main
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - run: |
          echo "event"
          echo "branch"
      - run: ls -l
        
